# Generated by Django 3.0.7 on 2022-07-20 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.CharField(max_length=100)),
                ('procedure_date', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_procedures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Patient Procedures',
            },
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction_msg', models.TextField(max_length=1000)),
                ('completed', models.BooleanField(default=False)),
                ('due_date', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_instructions', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_instructions', to='data.Procedure')),
            ],
            options={
                'verbose_name_plural': 'Patient Instructions',
            },
        ),
    ]
